version: "3.9"

services:
   nginx:
    build: .
    container_name: portfolio-nginx
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    networks: [appnet]
    ports: ["8001:8001"]

networks:
  appnet:
